apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-posts-mongo
  labels:
    app: realtime-posts
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-posts
      component: mongo
  template:
    metadata:
      labels:
        app: realtime-posts
        component: mongo
    spec:
      containers:
      - name: realtime-posts-mongo
        image: mongo
        ports:
          - containerPort: 27017
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_INITDB_DATABASE
          - name: MONGO_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: MONGO_PASSWORD
        volumeMounts:
          - name: init-script
            mountPath: /docker-entrypoint-initdb.d/init-mongo.js
            subPath: init-mongo.js
      volumes:
        - name: init-script
          configMap:
            name: mongo-config
