apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: realtime-posts
    component: frontend-service
spec:
  selector:
    app: realtime-posts
    component: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer